name: Update Solcast Forecast
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python script
        env:
          SOLCAST_API_KEY: ${{ secrets.SOLCAST_API_KEY }}
          SOLCAST_LATITUDE: ${{ secrets.SOLCAST_LATITUDE }}
          SOLCAST_LONGITUDE: ${{ secrets.SOLCAST_LONGITUDE }}
          SOLCAST_RESOURCE_ID: ${{ secrets.SOLCAST_RESOURCE_ID }}
          GDRIVE_WEBAPP_URL: ${{ secrets.GDRIVE_WEBAPP_URL }}
          GDRIVE_UPLOAD_TOKEN: ${{ secrets.GDRIVE_UPLOAD_TOKEN }}
        run: python solcast_api.py
      
